title: Bosque Language Blog
description: Blog for the Bosque language and Platform
author: "Mark Marron"

theme: minima

base_url: /gh-pages-minima-starter
repository: https://github.com/BosqueLanguage/bosquelanguage.github.io

# Minima social links
github_username: BosqueLanguage
twitter_username: BosqueLanguage

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
